name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Authenticate npm
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
          echo "NPM_TOKEN is NOT set value - ${{secrets.NPM_TOKEN}} and GT_TOKEN - ${{ secrets.GH_TOKEN }}"
          exit 1
          else
            echo "NPM_TOKEN is set"
          fi
          echo "//registry.npmjs.org/:_authToken=$" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ${{ runner.temp }}/.npmrc
          cat ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
