name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:  # Set environment variables at the job level
      NPM_TOKEN: ${{ env.NPM_TOKEN }}  # Assuming NPM_TOKEN is set in your runner's environment
      GH_TOKEN: ${{ env.GH_TOKEN }}  # Assuming GH_TOKEN is set in your runner's environment
      NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}  # Assuming NODE_AUTH_TOKEN is set in your runner's environment
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
    
      - name: Authenticate npm
        run: echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm install
        
      - name: Run semantic-release
        run: npx semantic-release
  
      - name: Publish to npm
        run: npm publish
